#!/bin/bash
# Ce script crée la DB airflow_db en plus de olist_dw
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE airflow_db;
    CREATE DATABASE olist_dw;
    GRANT ALL PRIVILEGES ON DATABASE airflow_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE olist_dw TO $POSTGRES_USER;
EOSQL

echo "✅ Databases olist_dw and airflow_db created successfully"