#just for tac
statistics=true
job=dim_product
jobVersion=0.1
date=2026-05-13 191948978
contextName=Default
jobId=_ISGP0CeEEfGtbuKs6MuoKA
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=MYFIRSTPROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=