#just for tac
statistics=true
job=Sa_items
jobVersion=0.1
date=2026-05-12 221902739
contextName=Default
jobId=_tJ3DACbaEfGtbuKs6MuoKA
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=MYFIRSTPROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=