#just for tac
statistics=true
job=fait_vente
jobVersion=0.1
date=2026-05-13 131931554
contextName=Default
jobId=_1U6DsCecEfGtbuKs6MuoKA
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=MYFIRSTPROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=