#just for tac
statistics=true
job=dim_client
jobVersion=0.1
date=2026-05-13 184800695
contextName=Default
jobId=_CIElgCbfEfGtbuKs6MuoKA
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=MYFIRSTPROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=