#just for tac
statistics=true
job=dim_date
jobVersion=0.1
date=2026-05-13 131754622
contextName=Default
jobId=_ZA9t8CeREfGtbuKs6MuoKA
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=MYFIRSTPROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=